# Generated by Django 5.1.3 on 2024-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_gaminglaptop_laptop_mackbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaminglaptop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC')], default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC')], default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='mackbook',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC')], default='N/A', max_length=200),
        ),
    ]
