# Generated by Django 5.1.3 on 2024-11-19 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_cpucooler_dekstopram_graphicscard_laptop_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('model_title', models.CharField(default='blank', max_length=200)),
                ('brand_name', models.CharField(default='blank', max_length=200)),
                ('type', models.CharField(default='N/A', max_length=30)),
                ('size', models.CharField(default='N/A', max_length=30)),
                ('interface', models.CharField(default='N/A', max_length=100)),
                ('buffer_size', models.CharField(default='N/A', max_length=30)),
                ('rpm_class', models.CharField(default='N/A', max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('regular_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('warranty', models.CharField(blank=True, max_length=1, null=True)),
                ('product_catagory', models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC')], default='N/A', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolidDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('model_title', models.CharField(default='blank', max_length=200)),
                ('brand_name', models.CharField(default='blank', max_length=200)),
                ('type', models.CharField(default='N/A', max_length=30)),
                ('size', models.CharField(default='N/A', max_length=30)),
                ('interface', models.CharField(default='N/A', max_length=100)),
                ('buffer_size', models.CharField(default='N/A', max_length=30)),
                ('rpm_class', models.CharField(default='N/A', max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('regular_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('warranty', models.CharField(blank=True, max_length=1, null=True)),
                ('product_catagory', models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC')], default='N/A', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='laptop_ram',
            old_name='interface',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='laptop_ram',
            name='buffer_size',
        ),
        migrations.RemoveField(
            model_name='laptop_ram',
            name='rpm_class',
        ),
        migrations.AddField(
            model_name='laptop_ram',
            name='latency',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='laptop_ram',
            name='operating_voltage',
            field=models.TextField(default='N/A'),
        ),
    ]
