# Generated by Django 5.1.3 on 2024-11-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_harddrive_soliddrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpucooler',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='dekstopram',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamingdesktop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='gaminglaptop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='imacdekstop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop_ram',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='mackbook',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='processore',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='soliddrive',
            name='product_catagory',
            field=models.CharField(choices=[('DEKSTOP', 'DEKSTOP'), ('GAMINGDEKSTOP', 'GAMINGDEKSTOP'), ('IMAC', 'IMAC'), ('LAPTOP', 'LAPTOP'), ('GAMINGLAPTOP', 'GAMINGLAPTOP'), ('PROCESSOR', 'PROCESSOR'), ('CPU COOLER', 'CPU COOLER'), ('POWER SUPPLY', 'POWER SUPPLY'), ('HDD', 'HDD'), ('SDD', 'SDD'), ('GRAPHICS CARD', 'GRAPHICA CARD'), ('DEKSTOP RAM', 'DEKSTOP RAM'), ('LAPTOP RAM', 'LAPTOP RAM')], default='N/A', max_length=200),
        ),
    ]
